### ISSUE TITLE
Blank screen

### ISSUE THREAD

**Issue by uthynauta** [polmes/xflr5-ubuntu#1]
Hi, after compiling and running correctly XFLR5 it only appears as a blank screen, what should I be seeing? Mi OS is Ubuntu 16.04. Thank you in advance.
![screenshot from 2018-06-10 12-41-18](https://user-images.githubusercontent.com/23223372/41204561-a6599d2e-6cab-11e8-87bc-656a68cfe86c.png)

**Comment by polmes** [comment]
Hmm.. I think this is actually the expected behavior. You have to go into the menu and select File > Direct Foil Design (or any of the other design options) to see the main program.

Let me know if that is the case,

**Comment by marcovanderbijl** [comment]
You are missing the menubar, this is probably confusing you.
In Ubuntu they use a global menu (I really dislike that as it interrupts the work flow if you work with multiple applications opened).
Go to All Settings , Appearance (where you can select a wallpaper), tab behaviour, Show menu for windows, set it to 'in windows title bar'.

**Comment by polmes** [comment]
Indeed, @uthynauta, you can also try @marcovanderbijl's suggesiton if you are new to Ubuntu and the global menu.

Let me know if it's working now for you so I can close the issue,

**Comment by uthynauta** [comment]
Thank you so much, indeed I'm new to ubuntu, but I found it now, thanks for directing a n00b as me. Cheers.

**Comment by polmes** [comment]
Hahaha no problem!
