### ISSUE TITLE
lingl-dev

### ISSUE THREAD

**Issue by marcovanderbijl** [polmes/xflr5-ubuntu#2]
instructions for installing dependencies:
lingl-dev --> cant find package and it seems not to be needed for installation.

also I installed newest Qt 5.11.1 (instead of 5.11.0) that worked fine.
and I use Linux Mint 18 Sylvia (distro based on Ubuntu 16.04) without a problem.

thanks for the instructions got a brand new XFLR5 working!

**Comment by polmes** [comment]
Yup, I'm not sure where the `lingl-dev` dependency came from when I first wrote the instructions, but I just checked and it's not installed on my system anymore either, so I'm removing it from the instructions in 717108857ba71e3e0f8ffe3c0f249dc2606da2c2.

Thanks for letting me know,
