### ISSUE TITLE
Can't make (maybe missing dependency?)

### ISSUE THREAD

**Issue by trilbytim** [polmes/xflr5-ubuntu#4]
My attempt to make this is ending with:

`g++: error: /home/timbo/anaconda3/bin/../x86_64-conda-linux-gnu/sysroot/usr/lib64/libGL.so: No such file or directory
make[1]: *** [Makefile:1442: xflr5] Error 1
make[1]: Leaving directory '/home/timbo/software/xflr5/xflr5-ubuntu/xflr5/xflr5v6'
make: *** [Makefile:73: sub-xflr5v6-make_first] Error 2
`
I'm guessing this a missing dependency? I installed all the packages listed in the Readme.

**Comment by polmes** [comment]
Interesting… the `libgl` dependency should have taken care of that. However, it appears that you are running the build tools (`make`, `g++`) from an anaconda environment, which I believe won’t use the same operating system libraries.

Do you have an anaconda environment activated? You can typically exit one of those via `conda deactivate`, and after that you should be able to build everything from scratch correctly.

Let me know if that helps!

**Comment by trilbytim** [comment]
Thank you, yes that has worked, good work on making this available for us, thank you :+1:
